//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalLoanAndDepositsPerBranch
    {
        public string bname { get; set; }
        public Nullable<decimal> totalloans { get; set; }
        public Nullable<decimal> deposits { get; set; }
    }
}
